/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as ApiGenerateDamageImageRouteImport } from './routes/api/generate-damage-image'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated/audit'
import { Route as AuthenticatedClaimsNewRouteImport } from './routes/_authenticated/claims.new'
import { Route as AuthenticatedClaimsIdRouteImport } from './routes/_authenticated/claims.$id'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as AuthenticatedClaimsIdReviewRouteImport } from './routes/_authenticated/claims.$id.review'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiGenerateDamageImageRoute = ApiGenerateDamageImageRouteImport.update({
  id: '/api/generate-damage-image',
  path: '/api/generate-damage-image',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClaimsNewRoute = AuthenticatedClaimsNewRouteImport.update({
  id: '/claims/new',
  path: '/claims/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClaimsIdRoute = AuthenticatedClaimsIdRouteImport.update({
  id: '/claims/$id',
  path: '/claims/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedClaimsIdReviewRoute =
  AuthenticatedClaimsIdReviewRouteImport.update({
    id: '/review',
    path: '/review',
    getParentRoute: () => AuthenticatedClaimsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/api/generate-damage-image': typeof ApiGenerateDamageImageRoute
  '/claims/$id': typeof AuthenticatedClaimsIdRouteWithChildren
  '/claims/new': typeof AuthenticatedClaimsNewRoute
  '/claims/$id/review': typeof AuthenticatedClaimsIdReviewRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/api/generate-damage-image': typeof ApiGenerateDamageImageRoute
  '/': typeof AuthenticatedIndexRoute
  '/claims/$id': typeof AuthenticatedClaimsIdRouteWithChildren
  '/claims/new': typeof AuthenticatedClaimsNewRoute
  '/claims/$id/review': typeof AuthenticatedClaimsIdReviewRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/api/generate-damage-image': typeof ApiGenerateDamageImageRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/claims/$id': typeof AuthenticatedClaimsIdRouteWithChildren
  '/_authenticated/claims/new': typeof AuthenticatedClaimsNewRoute
  '/_authenticated/claims/$id/review': typeof AuthenticatedClaimsIdReviewRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/audit'
    | '/api/generate-damage-image'
    | '/claims/$id'
    | '/claims/new'
    | '/claims/$id/review'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/audit'
    | '/api/generate-damage-image'
    | '/'
    | '/claims/$id'
    | '/claims/new'
    | '/claims/$id/review'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/audit'
    | '/api/generate-damage-image'
    | '/_authenticated/'
    | '/_authenticated/claims/$id'
    | '/_authenticated/claims/new'
    | '/_authenticated/claims/$id/review'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiGenerateDamageImageRoute: typeof ApiGenerateDamageImageRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/generate-damage-image': {
      id: '/api/generate-damage-image'
      path: '/api/generate-damage-image'
      fullPath: '/api/generate-damage-image'
      preLoaderRoute: typeof ApiGenerateDamageImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/claims/new': {
      id: '/_authenticated/claims/new'
      path: '/claims/new'
      fullPath: '/claims/new'
      preLoaderRoute: typeof AuthenticatedClaimsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/claims/$id': {
      id: '/_authenticated/claims/$id'
      path: '/claims/$id'
      fullPath: '/claims/$id'
      preLoaderRoute: typeof AuthenticatedClaimsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/claims/$id/review': {
      id: '/_authenticated/claims/$id/review'
      path: '/review'
      fullPath: '/claims/$id/review'
      preLoaderRoute: typeof AuthenticatedClaimsIdReviewRouteImport
      parentRoute: typeof AuthenticatedClaimsIdRoute
    }
  }
}

interface AuthenticatedClaimsIdRouteChildren {
  AuthenticatedClaimsIdReviewRoute: typeof AuthenticatedClaimsIdReviewRoute
}

const AuthenticatedClaimsIdRouteChildren: AuthenticatedClaimsIdRouteChildren = {
  AuthenticatedClaimsIdReviewRoute: AuthenticatedClaimsIdReviewRoute,
}

const AuthenticatedClaimsIdRouteWithChildren =
  AuthenticatedClaimsIdRoute._addFileChildren(
    AuthenticatedClaimsIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedClaimsIdRoute: typeof AuthenticatedClaimsIdRouteWithChildren
  AuthenticatedClaimsNewRoute: typeof AuthenticatedClaimsNewRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedClaimsIdRoute: AuthenticatedClaimsIdRouteWithChildren,
  AuthenticatedClaimsNewRoute: AuthenticatedClaimsNewRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiGenerateDamageImageRoute: ApiGenerateDamageImageRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
